### ISSUE TITLE
Optional XML validation

### ISSUE THREAD

**Issue by vtisnado** [saqueib/qrss#1]
Hey @saqueib nice work!

I'm just wondering if you can made the xml validation optional like cache, so we can use the library to parse all kind of xml files.

Maybe adding something like this:

`private $no_validate = false;`

```
public function novalidate()
    {
        $this->no_validate = true;
        return $this;
    }
```

```
        if( ! $this->no_validate ) {
            return ($rss && $rss->channel) ? $rss : false;
        }
        return ($rss);
```

Thanks in advanced.

**Comment by saqueib** [comment]
Good Idea, I will do it, if you can make a pull request it will be super @vtisnado
